/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.SwingConstants;
import token.error;
import token.token;

/**
 *
 * @author AndaryuS
 */
public class pantallaReportes extends javax.swing.JFrame {

    /**
     * Creates new form pantallaReportes
     */
    ArrayList<token> tokens;
    ArrayList<error> errores;
    ArrayList<String>bitacora;
    JFrame pantallaHome;
    
    
    public pantallaReportes(JFrame home,ArrayList tokensR, ArrayList erroresR, ArrayList bitacoraR) {
        initComponents();
        this.pantallaHome=home;
        this.setExtendedState(MAXIMIZED_BOTH);
        this.tokens = tokensR;
        this.errores = erroresR;
        this.bitacora=bitacoraR;
        activarBotones();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInferior = new javax.swing.JPanel();
        jButtonAtras = new javax.swing.JButton();
        jPanelDerecho = new javax.swing.JPanel();
        jPanelSuperior = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelIzquierdo = new javax.swing.JPanel();
        jPanelCentral = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonReporteTokens = new javax.swing.JButton();
        jButtonReporteErrores = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonBitacora = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelInferior.setBackground(new java.awt.Color(0, 153, 255));

        jButtonAtras.setText("Atras");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInferiorLayout = new javax.swing.GroupLayout(jPanelInferior);
        jPanelInferior.setLayout(jPanelInferiorLayout);
        jPanelInferiorLayout.setHorizontalGroup(
            jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInferiorLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButtonAtras)
                .addContainerGap(606, Short.MAX_VALUE))
        );
        jPanelInferiorLayout.setVerticalGroup(
            jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInferiorLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButtonAtras)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelInferior, java.awt.BorderLayout.PAGE_END);

        jPanelDerecho.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanelDerechoLayout = new javax.swing.GroupLayout(jPanelDerecho);
        jPanelDerecho.setLayout(jPanelDerechoLayout);
        jPanelDerechoLayout.setHorizontalGroup(
            jPanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelDerechoLayout.setVerticalGroup(
            jPanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelDerecho, java.awt.BorderLayout.LINE_END);

        jPanelSuperior.setBackground(new java.awt.Color(0, 153, 255));

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("MesloLGS NF", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Reportes");
        jLabelTitulo.setToolTipText("");
        jLabelTitulo.setHorizontalAlignment(SwingConstants.CENTER);
        jLabelTitulo.setVerticalAlignment(SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelSuperiorLayout = new javax.swing.GroupLayout(jPanelSuperior);
        jPanelSuperior.setLayout(jPanelSuperiorLayout);
        jPanelSuperiorLayout.setHorizontalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
            .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelTitulo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelSuperiorLayout.setVerticalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelTitulo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanelSuperior, java.awt.BorderLayout.PAGE_START);

        jPanelIzquierdo.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanelIzquierdoLayout = new javax.swing.GroupLayout(jPanelIzquierdo);
        jPanelIzquierdo.setLayout(jPanelIzquierdoLayout);
        jPanelIzquierdoLayout.setHorizontalGroup(
            jPanelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelIzquierdoLayout.setVerticalGroup(
            jPanelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelIzquierdo, java.awt.BorderLayout.LINE_START);

        jPanelCentral.setBackground(new java.awt.Color(0, 153, 255));
        jPanelCentral.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jButtonReporteTokens.setText("Reporte Tokens");
        jButtonReporteTokens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReporteTokensActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReporteTokens);

        jButtonReporteErrores.setText("Reporte Errores");
        jButtonReporteErrores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReporteErroresActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReporteErrores);

        jPanelCentral.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jButtonBitacora.setText("Bitacora");
        jButtonBitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBitacoraActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonBitacora);

        jPanelCentral.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReporteTokensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReporteTokensActionPerformed
        // TODO add your handling code here:
        reporteTokens reporte = new reporteTokens(this,tokens);
        this.setVisible(false);
        reporte.setVisible(true);

    }//GEN-LAST:event_jButtonReporteTokensActionPerformed

    private void jButtonReporteErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReporteErroresActionPerformed
        // TODO add your handling code here:
        reporteErrores reporte = new reporteErrores(this,errores);
        this.setVisible(false);
        reporte.setVisible(true);

    }//GEN-LAST:event_jButtonReporteErroresActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        // TODO add your handling code here:
        pantallaHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonBitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBitacoraActionPerformed
        // TODO add your handling code here:
        bitacoraUI bitacoraV = new bitacoraUI(this, tokens,this.bitacora);
        bitacoraV.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButtonBitacoraActionPerformed

    private void activarBotones() {
        if (tokens.isEmpty() || !errores.isEmpty()) {
            jButtonReporteTokens.setEnabled(false);
            jButtonBitacora.setEnabled(false);
        }

        if (errores.isEmpty() && !tokens.isEmpty() ) {
            jButtonReporteErrores.setEnabled(false);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonBitacora;
    private javax.swing.JButton jButtonReporteErrores;
    private javax.swing.JButton jButtonReporteTokens;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelDerecho;
    private javax.swing.JPanel jPanelInferior;
    private javax.swing.JPanel jPanelIzquierdo;
    private javax.swing.JPanel jPanelSuperior;
    // End of variables declaration//GEN-END:variables
}
